
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          #- not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('my_first_dbt_model')
              field: id

  - name: cumulative_orders_by_date
    description: "Snowflake DBT test"
    columns:
      - name: O_ORDERKEY
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
          - accepted_values:
              values: [1, 2]
              quote: false # makes sure that we are comparing strings. If strings, we can ignore this paramter

  - name: my_third_dbt_hidden_model

  - name: my_fourth_dbt_hidden_model
